/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleWhatWeDoRouteImport } from './routes/$locale.what-we-do'
import { Route as LocaleWorkRouteImport } from './routes/$locale.work'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCapabilitiesRouteImport } from './routes/admin.capabilities'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ProjectsSadatCityRoRouteImport } from './routes/projects.sadat-city-ro'
import { Route as LocaleWhatWeDoIndexRouteImport } from './routes/$locale.what-we-do.index'
import { Route as LocaleWhatWeDoSectorRouteImport } from './routes/$locale.what-we-do.$sector'
import { Route as LocaleWorkIndexRouteImport } from './routes/$locale.work.index'
import { Route as LocaleWorkSlugRouteImport } from './routes/$locale.work.$slug'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWhatWeDoRoute = LocaleWhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWorkRoute = LocaleWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapabilitiesRoute = AdminCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSadatCityRoRoute = ProjectsSadatCityRoRouteImport.update({
  id: '/projects/sadat-city-ro',
  path: '/projects/sadat-city-ro',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWhatWeDoIndexRoute = LocaleWhatWeDoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleWhatWeDoRoute,
} as any)
const LocaleWhatWeDoSectorRoute = LocaleWhatWeDoSectorRouteImport.update({
  id: '/$sector',
  path: '/$sector',
  getParentRoute: () => LocaleWhatWeDoRoute,
} as any)
const LocaleWorkIndexRoute = LocaleWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleWorkRoute,
} as any)
const LocaleWorkSlugRoute = LocaleWorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleWorkRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/what-we-do': typeof LocaleWhatWeDoRouteWithChildren
  '/$locale/work': typeof LocaleWorkRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/projects/sadat-city-ro': typeof ProjectsSadatCityRoRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/what-we-do/$sector': typeof LocaleWhatWeDoSectorRoute
  '/$locale/work/$slug': typeof LocaleWorkSlugRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/$locale/what-we-do/': typeof LocaleWhatWeDoIndexRoute
  '/$locale/work/': typeof LocaleWorkIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/projects/sadat-city-ro': typeof ProjectsSadatCityRoRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$locale/what-we-do/$sector': typeof LocaleWhatWeDoSectorRoute
  '/$locale/work/$slug': typeof LocaleWorkSlugRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/$locale/what-we-do': typeof LocaleWhatWeDoIndexRoute
  '/$locale/work': typeof LocaleWorkIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/what-we-do': typeof LocaleWhatWeDoRouteWithChildren
  '/$locale/work': typeof LocaleWorkRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/projects/sadat-city-ro': typeof ProjectsSadatCityRoRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/what-we-do/$sector': typeof LocaleWhatWeDoSectorRoute
  '/$locale/work/$slug': typeof LocaleWorkSlugRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/$locale/what-we-do/': typeof LocaleWhatWeDoIndexRoute
  '/$locale/work/': typeof LocaleWorkIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/what-we-do'
    | '/$locale/work'
    | '/admin/audit'
    | '/admin/capabilities'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/login'
    | '/projects/sadat-city-ro'
    | '/$locale/'
    | '/admin/'
    | '/$locale/what-we-do/$sector'
    | '/$locale/work/$slug'
    | '/admin/projects/$projectId'
    | '/$locale/what-we-do/'
    | '/$locale/work/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/admin/audit'
    | '/admin/capabilities'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/login'
    | '/projects/sadat-city-ro'
    | '/$locale'
    | '/admin'
    | '/$locale/what-we-do/$sector'
    | '/$locale/work/$slug'
    | '/admin/projects/$projectId'
    | '/$locale/what-we-do'
    | '/$locale/work'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/what-we-do'
    | '/$locale/work'
    | '/admin/audit'
    | '/admin/capabilities'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin_/login'
    | '/projects/sadat-city-ro'
    | '/$locale/'
    | '/admin/'
    | '/$locale/what-we-do/$sector'
    | '/$locale/work/$slug'
    | '/admin/projects/$projectId'
    | '/$locale/what-we-do/'
    | '/$locale/work/'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProjectsSadatCityRoRoute: typeof ProjectsSadatCityRoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/what-we-do': {
      id: '/$locale/what-we-do'
      path: '/what-we-do'
      fullPath: '/$locale/what-we-do'
      preLoaderRoute: typeof LocaleWhatWeDoRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/work': {
      id: '/$locale/work'
      path: '/work'
      fullPath: '/$locale/work'
      preLoaderRoute: typeof LocaleWorkRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capabilities': {
      id: '/admin/capabilities'
      path: '/capabilities'
      fullPath: '/admin/capabilities'
      preLoaderRoute: typeof AdminCapabilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sadat-city-ro': {
      id: '/projects/sadat-city-ro'
      path: '/projects/sadat-city-ro'
      fullPath: '/projects/sadat-city-ro'
      preLoaderRoute: typeof ProjectsSadatCityRoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/what-we-do/': {
      id: '/$locale/what-we-do/'
      path: '/'
      fullPath: '/$locale/what-we-do/'
      preLoaderRoute: typeof LocaleWhatWeDoIndexRouteImport
      parentRoute: typeof LocaleWhatWeDoRoute
    }
    '/$locale/what-we-do/$sector': {
      id: '/$locale/what-we-do/$sector'
      path: '/$sector'
      fullPath: '/$locale/what-we-do/$sector'
      preLoaderRoute: typeof LocaleWhatWeDoSectorRouteImport
      parentRoute: typeof LocaleWhatWeDoRoute
    }
    '/$locale/work/': {
      id: '/$locale/work/'
      path: '/'
      fullPath: '/$locale/work/'
      preLoaderRoute: typeof LocaleWorkIndexRouteImport
      parentRoute: typeof LocaleWorkRoute
    }
    '/$locale/work/$slug': {
      id: '/$locale/work/$slug'
      path: '/$slug'
      fullPath: '/$locale/work/$slug'
      preLoaderRoute: typeof LocaleWorkSlugRouteImport
      parentRoute: typeof LocaleWorkRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface LocaleWhatWeDoRouteChildren {
  LocaleWhatWeDoSectorRoute: typeof LocaleWhatWeDoSectorRoute
  LocaleWhatWeDoIndexRoute: typeof LocaleWhatWeDoIndexRoute
}

const LocaleWhatWeDoRouteChildren: LocaleWhatWeDoRouteChildren = {
  LocaleWhatWeDoSectorRoute: LocaleWhatWeDoSectorRoute,
  LocaleWhatWeDoIndexRoute: LocaleWhatWeDoIndexRoute,
}

const LocaleWhatWeDoRouteWithChildren = LocaleWhatWeDoRoute._addFileChildren(
  LocaleWhatWeDoRouteChildren,
)

interface LocaleWorkRouteChildren {
  LocaleWorkSlugRoute: typeof LocaleWorkSlugRoute
  LocaleWorkIndexRoute: typeof LocaleWorkIndexRoute
}

const LocaleWorkRouteChildren: LocaleWorkRouteChildren = {
  LocaleWorkSlugRoute: LocaleWorkSlugRoute,
  LocaleWorkIndexRoute: LocaleWorkIndexRoute,
}

const LocaleWorkRouteWithChildren = LocaleWorkRoute._addFileChildren(
  LocaleWorkRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleWhatWeDoRoute: typeof LocaleWhatWeDoRouteWithChildren
  LocaleWorkRoute: typeof LocaleWorkRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleWhatWeDoRoute: LocaleWhatWeDoRouteWithChildren,
  LocaleWorkRoute: LocaleWorkRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCapabilitiesRoute: typeof AdminCapabilitiesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCapabilitiesRoute: AdminCapabilitiesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProjectsSadatCityRoRoute: ProjectsSadatCityRoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
